#!/usr/bin/env bash

#export DOCKER_CLI_EXPERIMENTAL=enabled

docker images
docker buildx build --pull --load --push --platform linux/amd64 -f ${DOCKERFILE_PATH} --tag ${IMAGE_NAME} . || docker images
echo "=========="
echo "build done"
echo "=========="
