#!/usr/bin/env bash

export DOCKER_CLI_EXPERIMENTAL=enabled

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx rm builder
docker buildx create --name builder --driver docker-container --use
docker buildx build --pull --platform linux/amd64,linux/armhf,linux/arm64 --tag $IMAGE_NAME .
