#!/usr/bin/env bash

#export DOCKER_CLI_EXPERIMENTAL=enabled

docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx create --name builder --driver docker-container --use
docker buildx inspect --bootstrap
echo "=============="
echo "pre-build done"
echo "=============="
