#!/usr/bin/env bash

export DOCKER_CLI_EXPERIMENTAL=enabled

echo "==============="
echo "pre_build start for ${IMAGE_NAME}"
echo "==============="
docker run --privileged --rm tonistiigi/binfmt --install all
docker run --privileged --rm multiarch/qemu-user-static --reset -p yes
docker buildx rm builder
docker buildx rm multiarch
docker buildx create --name miltiarch --driver docker-container --use
docker buildx ls
echo "============="
echo "pre_build end for ${IMAGE_NAME}"
echo "============="
